version: '2.1'

services:
  gateway:
    container_name: Quorum_Gateway
    build:
      dockerfile: Gateway.Dockerfile
      context: .
    networks:
      quorum_network:
        ipv4_address: 172.20.20.2
    depends_on:
      data_api:
        condition: service_started
      identity_api:
        condition: service_started
      client:
        condition: service_started
    ports:
      - 80:80
        
  message_bus:
    container_name: Quorum_Message_Bus
    image: rabbitmq:alpine
    networks:
      quorum_network:
        ipv4_address: 172.20.20.3
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 10s
      timeout: 10s
      retries: 5

  data_storage:
    container_name: Quorum_Data_Storage
    image: postgres:alpine
    environment:
      POSTGRES_DB: quorum_prod_storage
      POSTGRES_USER: quorum_prod_user
      POSTGRES_PASSWORD: Q2JahkZRHtY2GC2hKdhE7V3mgca8mgKm3nkfRFPvFAZ7
    networks:
      quorum_network:
        ipv4_address: 172.20.20.4
        
  identity_storage:
    container_name: Quorum_Identity_Storage
    image: postgres:alpine
    environment:
      POSTGRES_DB: quorum_prod_identity_storage
      POSTGRES_USER: quorum_prod_user
      POSTGRES_PASSWORD: U5kJDt5LvnWcmdNd64RrYDeKYHphTjScg5R7fNx6
    networks:
      quorum_network:
        ipv4_address: 172.20.20.5
        
  data_api:
    container_name: Quorum_Data_Api
    build:
      dockerfile: ../DataApi.Dockerfile
      context: ./Backend
    networks:
      quorum_network:
        ipv4_address: 172.20.20.6
    depends_on:
      data_storage:
        condition: service_started
      message_bus:
        condition: service_healthy
        
  identity_api:
    container_name: Quorum_Identity_Api
    build:
      dockerfile: ../IdentityApi.Dockerfile
      context: ./Backend
    restart: always
    networks:
      quorum_network:
        ipv4_address: 172.20.20.7
    depends_on:
      identity_storage:
        condition: service_started
      message_bus:
        condition: service_healthy

  client:
    container_name: Quorum_Client
    build:
      dockerfile: ../Client.Dockerfile
      context: ./Client
    networks:
      quorum_network:
        ipv4_address: 172.20.20.8
    depends_on:
      data_api:
        condition: service_started
      identity_api:
        condition: service_started

networks:
  quorum_network:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: 'false'
    ipam:
      driver: default
      config:
        - subnet: 172.20.20.0/24
